name: sqler
description: SQL Query Builder for Dart.
version: 0.1.0
homepage: https://github.com/tiagohm/sqler

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.12.0
